language: php
dist: trusty
sudo: false

matrix:
  include:
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/framework:5.5.*
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/framework:5.6.*
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/framework:5.7.*
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/framework:5.8.*
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/framework:6.0.*
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/framework:7.0.*
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/framework:8.0.*
    - php: 8.0
      env: FRAMEWORK_VERSION=laravel/framework:8.0.*
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/lumen-framework:5.5.*
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/lumen-framework:5.6.*
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/lumen-framework:5.7.*
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/lumen-framework:5.8.*
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/lumen-framework:6.0.*
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/lumen-framework:7.0.*
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/lumen-framework:8.0.*
    - php: 8.0
      env: FRAMEWORK_VERSION=laravel/lumen-framework:8.0.*

before_install:
  - printf "\n" | pecl install swoole

install:
  - composer require "${FRAMEWORK_VERSION}" --no-update -n
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/php-coveralls -v
