name: tests

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: true
      matrix:
        include:
          - php: "7.4"
            framework: "laravel/framework:^8.0"
            swoole: "4.4.17"
          - php: "7.4"
            framework: "laravel/framework:^8.0"
            swoole: "4.8.13"
          - php: "8.0"
            framework: "laravel/framework:^8.0"
            swoole: "4.4.17"
          - php: "8.0"
            framework: "laravel/framework:^8.0"
            swoole: "4.8.13"
          - php: "8.0"
            framework: "laravel/framework:^9.0"
            swoole: "4.4.17"
          - php: "8.0"
            framework: "laravel/framework:^9.0"
            swoole: "4.8.13"
          - php: "8.1"
            framework: "laravel/framework:^10.0"
            swoole: "4.4.17"
          - php: "8.1"
            framework: "laravel/framework:^10.0"
            swoole: "4.8.13"
          - php: "8.2"
            framework: "laravel/framework:^10.0"
            swoole: "4.4.17"
          - php: "8.2"
            framework: "laravel/framework:^10.0"
            swoole: "4.8.13"

    name: PHP ${{ matrix.php }} (${{ matrix.framework }}) swoole-(${{ matrix.swoole }})

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: swoole-${{ matrix.swoole }}
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            composer require ${{ matrix.framework }} --no-update -n
            COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist -n -o

      - name: Execute tests
        run: vendor/bin/phpunit
